### ISSUE TITLE
CPP->CIN

### ISSUE THREAD

**Issue by Tiang-88** [viebel/blog.klipse.tech#1]
CPP->CIN
<img width="341" alt="image" src="https://github.com/viebel/blog.klipse.tech/assets/51110833/f975cedf-d756-4252-8073-894f83d4ddbd">

**Comment by viebel** [comment]
`cin` is not supported

**Comment by Tiang-88** [comment]
> `cin` 不支持

hello.Jscpp already supports cin. Can it be supported once，Cin is very important in C++

**Comment by viebel** [comment]
Feel free to open a PR on https://github.com/viebel/klipse
